---
- hosts: 127.0.0.1
  user: root

  tasks:
 
   - name: nano
     yum: name=nano state=installed

   - name: install python-selinux
     yum: pkg=libselinux-python state=latest

   - selinux: state=disabled



- include: user.yml
- include: docker.yml
- include: java.yml
- include: maven3.yml
