---
- hosts: localhost
  user: root

  vars:
   # version info
   maven_version: 3.1.1

   maven_min_memory: 256m
   maven_max_memory: 512m
   maven_install_dir: /usr/local/maven
   # "major" version. Shouldn't need to change this for a while...
   maven_major_version: 3

   maven_base_download_url: "http://apache.mirrors.tds.net/maven/maven-{{ maven_major_version }}/{{ maven_version }}/binaries/"
   maven_extracted_dirname: "apache-maven-{{ maven_version }}"
   maven_download_filename: "apache-maven-{{ maven_version }}-bin.tar.gz"
   maven_download_url: "{{ maven_base_download_url }}/{{ maven_download_filename }}"

  tasks:

   - name: Is maven currently installed?
     shell: "[ -d {{ maven_install_dir }}/{{ maven_extracted_dirname }} ] && echo 'Found' || echo ''"
     register: mvn_installed
     changed_when: mvn_installed.stdout == ""
     tags: maven

   - name: Create a maven directory
     file: path={{ maven_install_dir }} owner=root group=root mode=0775 state=directory
     when: (not mvn_installed.stdout)
     tags: maven

   - name: Download maven
     get_url: dest={{ maven_install_dir }}/{{ maven_download_filename }} url={{ maven_download_url }}
     when: (not mvn_installed.stdout)
     tags: maven

   - name: Extract maven archive file
     command: creates={{ maven_install_dir }}/{{ maven_extracted_dirname }} chdir={{ maven_install_dir }} tar zxvf {{ maven_install_dir }}/{{ maven_download_filename }} --owner=root
     when: (not mvn_installed.stdout)
     tags: maven

   - name: Create a maven latest symlink
     file: src={{ maven_install_dir }}/{{ maven_extracted_dirname }} dest={{ maven_install_dir }}/latest owner=root group=root state=link
     when: (not mvn_installed.stdout)
     tags: maven

   - name: Copy config maven.sh
     action: template src=etc_profiled_maven.sh.j2 dest=/etc/profile.d/maven.sh owner=root group=root mode=0644
     when: (not mvn_installed.stdout)
     tags: maven

   - name: Cleanup maven archive file
     file: path={{ maven_install_dir }}/{{ maven_download_filename }} state=absent
     when: (not mvn_installed.stdout)
     tags: maven


