---
- hosts: localhost
  user: root

  tasks:

   - name: be sure ntp is installed
     yum: pkg=ntp state=installed
     tags: ntp

   - name: be sure ntp is configured
     template: src=ntp.conf.j2 dest=/etc/ntp.conf
     notify:
      - name: restart ntpd
        service: name=ntpd state=restarted
     tags: ntp

   - name: be sure ntpd is running and enabled
     service: name=ntpd state=running enabled=yes
     tags: ntp
